language: python
env:
    - TOX_ENV=py27
    - TOX_ENV=docs
services:
  - mongodb
  - elasticsearch
  - neo4j
before_install:
    - sudo apt-get install python-dev
    - sudo apt-get install g++
    - sudo apt-get install libssl0.9.8
    - sudo apt-get install libgeoip1
    - sudo apt-get install libpcap0.8
    - wget https://s3-us-west-2.amazonaws.com/workbench-data/packages/Bro-2.2-Linux-x86_64_flex.deb
    - sudo dpkg -i Bro-2.2-Linux-x86_64_flex.deb
    - export PATH=/opt/bro/bin:$PATH
    - wget https://s3-us-west-2.amazonaws.com/workbench-data/memory_images/exemplar4.vmem -o workbench/data/memory_images/exemplar4.vmem
    - wget https://s3.amazonaws.com/workbench-wheels/py27/numpy-1.8.2-cp27-none-linux_x86_64.whl
install:
    - pip install tox
    - pip install coveralls
script: 
    - tox -e $TOX_ENV
after_success:
    - coveralls
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/c9330e06db1c989e043c
    on_success: always  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false

