language: python
python:
    - 2.7
env:
    - TOX_ENV=py26
    - TOX_ENV=py27
    - TOX_ENV=py32
    - TOX_ENV=py33
    - TOX_ENV=pypy
    - TOX_ENV=docs
    - TOX_ENV=pep8
services:
  - mongodb
  - elasticsearch
  - neo4j
before_install:
    - sudo apt-get install python-dev
    - sudo apt-get install g++
    - sudo apt-get install libssl0.9.8
    - sudo apt-get install libgeoip1
    - sudo apt-get install libpcap0.8
    - wget https://s3-us-west-2.amazonaws.com/workbench-data/packages/Bro-2.2-Linux-x86_64_flex.deb
    - sudo dpkg -i Bro-2.2-Linux-x86_64_flex.deb
    - export PATH=/opt/bro/bin:$PATH
#    - wget https://s3-us-west-2.amazonaws.com/workbench-data/mem_images/exemplar4.vmem -o data/memory_images/exemplar4.vmem
install:
    - pip install -r requirements.txt
    - pip install coveralls
    - pip install git+https://github.com/newbrough/coverage.git
script: 
    # - coverage run --source=workbench setup.py test
    - tox -e $TOX_ENV
after_success:
    - coveralls
