language: python
env:
    - TOX_ENV=py27
    - TOX_ENV=pypy
services:
  - mongodb
  - elasticsearch
  - neo4j
before_install:
    - sudo apt-get install python-dev
    - sudo apt-get install g++
    - sudo apt-get install libssl0.9.8
    - sudo apt-get install libgeoip1
    - sudo apt-get install libpcap0.8
    - wget https://s3-us-west-2.amazonaws.com/workbench-data/packages/Bro-2.2-Linux-x86_64_flex.deb
    - sudo dpkg -i Bro-2.2-Linux-x86_64_flex.deb
    - export PATH=/opt/bro/bin:$PATH
#    - wget https://s3-us-west-2.amazonaws.com/workbench-data/mem_images/exemplar4.vmem -o data/memory_images/exemplar4.vmem
install:
    - pip install tox
    - pip install coveralls
script: 
    # - coverage run --source=workbench setup.py test
    - tox -e $TOX_ENV
after_success:
    - coveralls
